#include "astLib.h"
int astXtndtr ( double cij[6], struct WCS wcsxy, struct WCS * wcsij )
/*
**  - - - - - - - - - -
**   a s t X t n d t r
**  - - - - - - - - - -
**
**  Extend a world coordinate system transformation to start from
**  instrumental i/j instead of focal-plane x/y.
**
**  GIVEN:
**    cij       double[6]  affine transformation, i/j to x/y
**    wcsxy     struct     WCS transformation (x/y to sky)
**
**  RETURNED (arguments):
**    wcsij     struct*    extended WCS structure (i/j to sky)
**
**  RETURNED (function value):
**              int        0 = OK
**
**  Defined in astLib.h:
**    WCS       struct     WCS transformation parameters
**
**  To guide potential non-Gemini-TCS users of this routine, here is
**  the present definition of the above.
**
**  struct WCS {
**        double ab0[2];      / * Celestial coordinates at x=y=0 * /
**        double coeffs[6];   / * Affine transformation coefficients * /
**  };
**
** Note:
**
**  The coefficients cij describe the affine transformation between
**  instrumental coordinates i/j (for example pixel coordinates in the
**  case of a CCD) and focal-plane coordinates x/y.  Writing cij[0-5]
**  as a,b,c,d,e,f:
**
**       x = a + bi + cj
**       y = d + ei + fj
**
**  The coefficients can be generated by calling astFitij, or
**  alternatively slaFitxy.
**
**  P.T.Wallace   16 April 1997
**
**  Copyright RAL 1997.  All rights reserved.
*/
{
   double a, b, c, d, e, f, A, B, C, D, E, F;


/* Copy the sky coordinates. */
   wcsij->ab0[0] = wcsxy.ab0[0];
   wcsij->ab0[1] = wcsxy.ab0[1];

/* Combine the affine transformations. */
   a = cij[0];
   b = cij[1];
   c = cij[2];
   d = cij[3];
   e = cij[4];
   f = cij[5];
   A = wcsxy.coeffs[0];
   B = wcsxy.coeffs[1];
   C = wcsxy.coeffs[2];
   D = wcsxy.coeffs[3];
   E = wcsxy.coeffs[4];
   F = wcsxy.coeffs[5];
   wcsij->coeffs[0] = A + B*a + C*d;
   wcsij->coeffs[1] = B*b + C*e;
   wcsij->coeffs[2] = B*c + C*f;
   wcsij->coeffs[3] = D + E*a + F*d;
   wcsij->coeffs[4] = E*b + F*e;
   wcsij->coeffs[5] = E*c + F*f;

   return 0;
}
